apps/central/urls.py
from django.urls import re_path
from django.views.generic import TemplateView


app_name = 'central'
urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='central/index.html'), name='index'),
]

apps/myauth/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    RegisterView
)


app_name = 'myauth'
urlpatterns = (
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name='registration')
)

conf/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path


admin.site.site_header = 'Media project'
admin.site.site_title = 'Media project'

urlpatterns = [
    re_path(r'^', include('apps.central.urls', namespace='central')),
    path('admin/', admin.site.urls),
    path('auth/', include('apps.myauth.urls', namespace='myauth')),
    path('digests/', include('apps.digests.urls', namespace='digests')),
    path('vk_monitoring/', include('apps.vk_monitoring.urls', namespace='vk_monitoring')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/_navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <div class="container"> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar18">
  <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbar18"> <a class="navbar-brand d-none d-md-block" href="/">
      <i class="fa d-inline fa-lg fa-circle"></i>
      <b>MediaProject</b>
      </a>
      <ul class="navbar-nav mx-auto">
        <li class="nav-item"> <a class="nav-link text-white" href="/admin">Dashboard</a> </li>
        <li class="nav-item"> <a class="nav-link" href="{% url 'digests:index' %}">Digests</a> </li>
        <li class="nav-item"> <a class="nav-link" href="{% url 'vk_monitoring:index' %}">Vk monitoring</a> </li>
      </ul>
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
          <li class="nav-item"> <a class="nav-link" href="{% url 'myauth:logout' %}">Log out</a> </li>
        {% else %}
          <li class="nav-item"> <a class="nav-link" href="{% url 'myauth:login' %}">Log in</a> </li>
          <li class="nav-item"> <a class="nav-link text-white" href="{% url 'myauth:registration' %}">Register</a> </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>